<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-F9KQSCF" failures="1" tests="3" name="Error validations" time="53.537" errors="0" timestamp="2022-10-12T00:02:44 IST">
  <testcase classname="amolseleniumfirstpack.tests.ErrorValidationsTest" name="validateCartProduct" time="1.3">
    <skipped/>
  </testcase> <!-- validateCartProduct -->
  <testcase classname="amolseleniumfirstpack.tests.ErrorValidationsTest" name="validateCartProduct" time="34.002">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at amolseleniumfirstpack.tests.ErrorValidationsTest.validateCartProduct(ErrorValidationsTest.java:52)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- validateCartProduct -->
  <testcase classname="amolseleniumfirstpack.tests.ErrorValidationsTest" name="validateLogin" time="0.38"/>
</testsuite> <!-- Error validations -->
